### ISSUE TITLE
How do LaTeX algorithms render on the pages?

### ISSUE THREAD

**Issue by gchhablani** [fjp/fjp.github.io#5]
Hi,

I was trying to understand the code specifically on https://github.com/fjp/fjp.github.io/blob/master/collections/_posts/localization/2019-03-15-monte-carlo-localization.md

I wanted to know how does rendering of algorithms take place in the Monte-Carlo-Localization file.

Thanks,
Gunjan

**Comment by fjp** [comment]
Hi Gunjan,

I am using [katex](https://katex.org/) for the LaTeX algorithms. I've included the source here in my [public folder](https://github.com/fjp/fjp.github.io/tree/master/public/katex).

Best
Franz

**Comment by gchhablani** [comment]
Thanks @fjp
